poses:
  - start_time: 0
    pose:
      header:
        frame_id: "map"
      pose:
        position: {x: 1.5, y: 0.0, z: 0.0}
        orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
  - start_time: 10
    pose:
      header:
        frame_id: "map"
      pose:
        position: {x: 1.5, y: -2.0, z: 0.0}
        orientation: {x: 0.0, y: 0.0, z: -0.707107, w: 0.707107}
  - start_time: 5
    pose:
      header:
        frame_id: "map"
      pose:
        position: {x: 0.0, y: 0.0, z: 0.0}
        orientation: {x: 0.0, y: 0.0, z: 0.707107, w: 0.707107}
map:
  - from_idex: 0
    play_id: 2
    play_percent: 0.0
  - from_idex: 0
    play_id: 1
    play_percent: 1.0

  - from_idex: 1
    play_id: 3
    play_percent: 0.5
  - from_idex: 1
    play_id: 3
    play_percent: 1.0
  
  - from_idex: 2
    play_id: 4
    play_percent: 0.5
  - from_idex: 2
    play_id: 1
    play_percent: 1.0